# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empFirstName', models.CharField(max_length=36)),
                ('empLastName', models.CharField(max_length=36)),
                ('empEmail', models.CharField(max_length=36, unique=True)),
                ('empPassword', models.CharField(default=b'pass', max_length=36)),
                ('empDesignation', models.CharField(choices=[(b'driver', b'Driver'), (b'ja', b'Junior Assistant'), (b'sa', b'Senior Assistant'), (b'jt', b'Junior Technician'), (b'st', b'Senior Technician'), (b'ar', b'Assistant Registrar'), (b'dr', b'Deputy Registrar'), (b'rr', b'Registrar'), (b'Research Engineer', b'Research Engineer'), (b'Assistant Professor', b'Assistant Professor'), (b'Associate Professor', b'Associate Professor'), (b'Professor', b'Professor')], max_length=36)),
                ('empDepartment', models.CharField(choices=[(b'iwd', b'IWD'), (b'et', b'Establishment'), (b'library', b'Library'), (b'pc', b'Placement Cell'), (b'acad', b'Academics'), (b'ns', b'Natural Science'), (b'cse', b'CSE'), (b'ece', b'ECE'), (b'me', b'ME'), (b'otd', b'Office of Dean'), (b'fna', b'Finance & Accounts'), (b'directorate', b'Directorate')], max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeHierarchy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLeaveAuthority',
            fields=[
                ('authID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('authDesignation', models.CharField(choices=[(b'rr', b'Registrar'), (b'director', b'Director'), (b'ccc', b'Coordinator Computer Center'), (b'wi', b'Workshop In-charge'), (b'headns', b'HOD NS'), (b'hodcse', b'HOD CSE'), (b'hodece', b'HOD ECE'), (b'hodme', b'HOD ME'), (b'deanacad', b'Dean Academics'), (b'deanstudents', b'Dean Students'), (b'deanRSPC', b'Dean RSPC')], max_length=18)),
                ('empActingAuthStatus', models.BooleanField(default=False)),
                ('authActingID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ELA_authActingID', to='fusion.Employee')),
                ('authHeadID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ELA_authHeadID', to='fusion.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLeaveBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empCL', models.IntegerField()),
                ('empCOL', models.IntegerField()),
                ('empEL', models.IntegerField()),
                ('empRH', models.IntegerField()),
                ('empSCL', models.IntegerField()),
                ('empVL', models.IntegerField()),
                ('empID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fusion.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLeaveDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empLeaveType', models.CharField(max_length=5)),
                ('empLeaveFrom', models.DateField()),
                ('empLeaveTo', models.DateField()),
                ('empLeaveDuration', models.IntegerField()),
                ('empLeaveStatus', models.IntegerField(default=0)),
                ('empID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fusion.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeStationLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empStationLeave', models.BooleanField(default=False)),
                ('empStationAddress', models.CharField(max_length=150)),
                ('empLeaveID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fusion.EmployeeLeaveDetails')),
            ],
        ),
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HolidayType', models.CharField(max_length=3)),
                ('HolidayFrom', models.DateField()),
                ('HolidayTo', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='employeehierarchy',
            name='empHeadAuthID1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EH_empAuthID1', to='fusion.EmployeeLeaveAuthority'),
        ),
        migrations.AddField(
            model_name='employeehierarchy',
            name='empHeadAuthID2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EH_empAuthID2', to='fusion.EmployeeLeaveAuthority'),
        ),
        migrations.AddField(
            model_name='employeehierarchy',
            name='empID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fusion.Employee'),
        ),
    ]
