# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empDepartment',
            field=models.CharField(choices=[(b'iwd', b'IWD'), (b'et', b'Establishment'), (b'library', b'Library'), (b'pc', b'Placement Cell'), (b'acad', b'Academics'), (b'ns', b'Natural Science'), (b'cse', b'CSE'), (b'ece', b'ECE'), (b'me', b'ME'), (b'otd', b'Office of Dean'), (b'fna', b'Finance and Accounts'), (b'directorate', b'Directorate')], max_length=36),
        ),
    ]
